apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node1
spec:
  selector:
    matchLabels:
      app: node1
  replicas: 1
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
      - name: node1
        image: mortenlyngosenquist/node:latest
        ports:
            - containerPort: 5000
        env:
        - name: NO_NODES
          value: "7"
        - name: NODE_ID
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: node1-svc
  labels:
    app: node1
spec:
  type: LoadBalancer
  ports:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: node1

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node2
spec:
  selector:
    matchLabels:
      app: node2
  replicas: 1
  template:
    metadata:
      labels:
        app: node2
    spec:
      containers:
      - name: node2
        image: mortenlyngosenquist/node:latest
        ports:
        - containerPort: 5000
        env:
        - name: NO_NODES
          value: "7"
        - name: NODE_ID
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: node2-svc
  labels:
    app: node2
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: node2

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node3
spec:
  selector:
    matchLabels:
      app: node3
  replicas: 1
  template:
    metadata:
      labels:
        app: node3
    spec:
      containers:
      - name: node3
        image: mortenlyngosenquist/node:latest
        ports:
        - containerPort: 5000
        env:
        - name: NO_NODES
          value: "7"
        - name: NODE_ID
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: node3-svc
  labels:
    app: node3
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: node3

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node4
spec:
  selector:
    matchLabels:
      app: node4
  replicas: 1
  template:
    metadata:
      labels:
        app: node4
    spec:
      containers:
      - name: node4
        image: mortenlyngosenquist/node:latest
        ports:
        - containerPort: 5000
        env:
        - name: NO_NODES
          value: "7"
        - name: NODE_ID
          value: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: node4-svc
  labels:
    app: node4
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: node4

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node5
spec:
  selector:
    matchLabels:
      app: node5
  replicas: 1
  template:
    metadata:
      labels:
        app: node5
    spec:
      containers:
      - name: node5
        image: mortenlyngosenquist/node:latest
        ports:
        - containerPort: 5000
        env:
        - name: NO_NODES
          value: "7"
        - name: NODE_ID
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: node5-svc
  labels:
    app: node5
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: node5

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node6
spec:
  selector:
    matchLabels:
      app: node6
  replicas: 1
  template:
    metadata:
      labels:
        app: node6
    spec:
      containers:
      - name: node6
        image: mortenlyngosenquist/node:latest
        ports:
        - containerPort: 5000
        env:
        - name: NO_NODES
          value: "7"
        - name: NODE_ID
          value: "6"
---
apiVersion: v1
kind: Service
metadata:
  name: node6-svc
  labels:
    app: node6
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: node6

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node7
spec:
  selector:
    matchLabels:
      app: node7
  replicas: 1
  template:
    metadata:
      labels:
        app: node7
    spec:
      containers:
      - name: node7
        image: mortenlyngosenquist/node:latest
        ports:
        - containerPort: 5000
        env:
        - name: NO_NODES
          value: "7"
        - name: NODE_ID
          value: "7"
---
apiVersion: v1
kind: Service
metadata:
  name: node7-svc
  labels:
    app: node7
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: node7



